# 此工作流使用未经 GitHub 认证的 Actions。
# 它们由第三方提供，并受单独的服务条款、隐私政策和支持文档管辖。

name: Scorecard supply-chain security

on:
  # 用于分支保护检查。仅支持默认分支。参见
  # https://github.com/ossf/scorecard/blob/main/docs/checks.md#branch-protection
  # 保证 Maintained 检查偶尔更新。参见
  # https://github.com/ossf/scorecard/blob/main/docs/checks.md#maintained
  branch_protection_rule:
  schedule:
    # 每周四 UTC 19:17 运行
    - cron: '17 19 * * 4'
  push:
    branches: [ "main"]
  workflow_dispatch:  # 允许手动触发

# 声明默认权限为只读
permissions: read-all

jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    # `publish_results: true` 仅在从默认分支运行时有效。如果禁用则可以移除此条件
    if: github.event.repository.default_branch == github.ref_name || github.event_name == 'pull_request'
    permissions:
      # 需要将结果上传到代码扫描仪表板
      security-events: write
      # 需要发布结果并获取徽章（参见下方的 publish_results）
      id-token: write
      # 如果在私有仓库中安装，请取消下面的权限注释
      # contents: read
      # actions: read

    steps:
      # 1. 安全加固 Runner
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit

      # 2. 检出代码
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      # 3. 运行分析
      - name: "Run analysis"
        uses: ossf/scorecard-action@f49aabe0b5af0936a0987cfb85d86b75731b0186 # v2.4.1
        with:
          results_file: results.sarif
          results_format: sarif
          # (可选) "write" PAT 令牌。如果满足以下条件，请取消下面的 `repo_token` 行注释：
          # - 您想要在*公共*仓库上启用 Branch-Protection 检查，或
          # - 您正在*私有*仓库上安装 Scorecard
          # 要创建 PAT，请按照 https://github.com/ossf/scorecard-action?tab=readme-ov-file#authentication-with-fine-grained-pat-optional 中的步骤操作
          # repo_token: ${{ secrets.SCORECARD_TOKEN }}

          # 公共仓库：
          #   - 将结果发布到 OpenSSF REST API 以便消费者轻松访问
          #   - 允许仓库包含 Scorecard 徽章
          #   - 参见 https://github.com/ossf/scorecard-action#publishing-results
          # 私有仓库：
          #   - 无论此处输入的值如何，`publish_results` 将始终设置为 `false`
          publish_results: true

          # (可选) 如果您有 .gitattributes 并标记文件为 export-ignore，请取消 file_mode 注释
          # file_mode: git

      # 4. 将结果上传为工件（可选）。注释掉将禁用 SARIF 格式的运行结果上传到仓库 Actions 标签页
      - name: "Upload artifact"
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: SARIF file
          path: results.sarif
          retention-days: 5

      # 5. 将结果上传到 GitHub 的代码扫描仪表板（可选）
      # 注释掉将禁用结果上传到仓库的代码扫描仪表板
      - name: "Upload to code-scanning"
        uses: github/codeql-action/upload-sarif@5d4e8d1aca955e8d8589aabd499c5cae939e33c7 # v4.31.9
        with:
          sarif_file: results.sarif